language: ruby
# needs a language, and python doesn't work on travis-osx

# let linux be Ubuntu 14.04 Trusty
sudo: required
dist: trusty

os:
    - linux
    - osx

before_script:
    - echo "$TRAVIS_OS_NAME"
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then sudo apt-get -f install locales build-essential automake subversion pkg-config gawk libtool apertium-all-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then brew install gperftools help2man icu4c perl518 gawk; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then ( svn co http://beta.visl.sdu.dk/svn/visl/tools/vislcg3/trunk vislcg3 && cd vislcg3 && CMAKE_PREFIX_PATH=/usr/local/opt/icu4c:"${CMAKE_PREFIX_PATH}" ./cmake.sh && make -j4 && sudo make install ); fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then ( svn co https://svn.code.sf.net/p/apertium/svn/trunk/lttoolbox/ && cd lttoolbox && ./autogen.sh && make -j4 && sudo make install ); fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then ( svn co https://svn.code.sf.net/p/apertium/svn/trunk/apertium/ && cd apertium && ./autogen.sh && make -j4 && sudo make install ); fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then ( svn co https://svn.code.sf.net/p/apertium/svn/trunk/apertium-lex-tools/ && cd apertium-lex-tools && ./autogen.sh && make -j4 && sudo make install ); fi

script:
    - t/regression-tests
