language: ruby
# needs a language, and python doesn't work on travis-osx

os:
    - linux
    - osx

before_script:
    - echo "$TRAVIS_OS_NAME"
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then sudo apt-get -f install locales build-essential automake subversion pkg-config gawk libtool apertium-all-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then sudo add-apt-repository -y ppa:dns/gnu; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then sudo apt-get update -qq; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then sudo apt-get install -qq -yy automake; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then brew install gperftools help2man pcre icu4c perl518 gawk; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then ( svn co http://beta.visl.sdu.dk/svn/visl/tools/vislcg3/trunk vislcg3 && cd vislcg3 && CMAKE_PREFIX_PATH=/usr/local/opt/icu4c:"${CMAKE_PREFIX_PATH}" ./cmake.sh && make -j4 && sudo make install ); fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then ( svn co https://svn.code.sf.net/p/apertium/svn/trunk/lttoolbox/ && cd lttoolbox && ./autogen.sh && make -j4 && sudo make install ); fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then ( svn co https://svn.code.sf.net/p/apertium/svn/trunk/apertium/ && cd apertium && ./autogen.sh && make -j4 && sudo make install ); fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then ( svn co https://svn.code.sf.net/p/apertium/svn/trunk/apertium-lex-tools/ && cd apertium-lex-tools && ./autogen.sh && make -j4 && sudo make install ); fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then ( svn co svn://svn.code.sf.net/p/hfst/code/trunk/hfst3 && cd hfst3 && ./autogen.sh && ./configure --enable-proc --without-foma --enable-lexc --enable-all-tools && make -j4 && sudo make install ); fi

script:
    - automake --version  
    - t/regression-tests
