language: ruby
# needs a language, and python doesn't work on travis-osx

# let linux be Ubuntu 14.04 Trusty
sudo: required
dist: trusty

os:
    - linux
    - osx

before_script:
    - echo "$TRAVIS_OS_NAME"
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then sudo apt-get -f install locales build-essential automake subversion pkg-config gawk libtool apertium-all-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then brew install gperftools help2man icu4c perl518 gawk; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then curl -Ss http://apertium.projectjj.com/osx/install-nightly.sh | sudo bash; fi

script:
    - t/regression-tests
