#+STARTUP: showall

* apertium-get

  This is a little script to quickly get an Apertium language pair
  (with its monolingual dependencies) set up for development. It's
  meant for developers and people interested in hacking on the
  language data; if you just want to run the newest translators you
  should use the [[http://wiki.apertium.org/wiki/Installation][nightly repositories]].

** Usage

   You'll need the newest Apertium development dependencies installed
   first, follow the "Prerequisites" step at
   http://wiki.apertium.org/wiki/Installation but just skip installing
   any language data in the "Minimal installation from SVN" step –
   that's what this script handles.

   Then, to install the pair "fie-bar" along with its data
   dependencies apertium-fie and apertium-bar, just do:

#+BEGIN_SRC sh
wget https://raw.githubusercontent.com/unhammer/apertium-get/master/apertium-get
chmod +x apertium-get
./apertium-get fie-bar
#+END_SRC

   The data will be placed under your current working directory. If
   you later run =apertium-get fie-fum= from the same directory, it'll
   just update apertium-fie, not redownload it (so you can actually
   use this script as a simple way to do =svn up && make= for a pair
   and its dependencies as well).
