name: apertium-get CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: |
           sudo apt-get -qy update
           sudo apt-get -qfy install wget ca-certificates
           wget -q https://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
           sudo apt-get -qfy install --no-install-recommends build-essential cmake python3 apertium-dev apertium-anaphora apertium-lex-tools apertium-recursive apertium-separable autoconf automake cg3-dev gawk git libhfst-dev libtool locales pkg-config
    - name: envvars
      run: export V=1 VERBOSE=1
    - name: cmake
      run: cmake .
    - name: build
      run: cmake --build . -v -j 4
    - name: test
      run: bash -x ./t/regression-tests
    - name: install
      run: sudo cmake --install .
